name: VarLight
version: "plugin.version"
author: shawlaf
main: me.shawlaf.varlight.spigot.VarLightPlugin
description: Turn Normal Blocks into Light Sources!
api-version: "1.21"
load: STARTUP

softdepend:
  - "Multiverse-Core"
  - "WorldEdit"
  - "WorldGuard"